services:
  bundler:
    build:
      context: .
      dockerfile: docker/json-bundler/Dockerfile
    image: myparcelcom/json-bundler:v7-dev
    working_dir: /opt/spec
    volumes:
      - .:/opt/spec

  carrier-specification:
    build:
      context: .
      dockerfile: docker/build/Dockerfile
    image: myparcelcom/carrier-specification:v9-dev
    volumes:
      - ./dist:/usr/share/nginx/html/dist/
      - ./src/index.html:/usr/share/nginx/html/index.html
      - ./src/myparcelcom.css:/usr/share/nginx/html/myparcelcom.css
      - ./src/myparcelcom.js:/usr/share/nginx/html/myparcelcom.js
    environment:
      SPEC_URL: /dist/swagger.json
      PAGE_FAVICON: favicon-16x16.png
    expose:
      - 80
    networks:
      - proxynet

  validator:
    image: swaggerapi/swagger-validator
    working_dir: /opt/spec
    volumes:
      - ./dist:/opt/spec

networks:
  proxynet:
    external: true
