version: '3'

services:
  bundler:
    build:
      context: ./docker/json-bundler
      dockerfile: Dockerfile
    image: myparcelcom/carrier-spec-bundler:v1-dev
    working_dir: /opt/spec
    volumes:
      - .:/opt/spec

  node:
    image: node:11.4
    working_dir: /opt/spec
    command: ./node_modules/.bin/gulp watch --port $GULP_PORT
    volumes:
      - .:/opt/spec
    ports:
      - $GULP_PORT:$GULP_PORT

  validator:
    image: swaggerapi/swagger-validator
    working_dir: /opt/spec
    volumes:
      - ./dist:/opt/spec
