#!/usr/bin/env bash

echo -e "\033[0;30;47m Bundling spec \033[0m"
${COMPOSE} run --rm bundler bash -c "
mkdir -p dist
json-refs resolve schema.json -f > dist/swagger.json
"

if [ "$(uname -s)" == "Linux" ]; then
  echo -e "\033[0;30;47m Fixing file ownership for Linux \033[0m"
  ${COMPOSE} run --rm bundler chown -R $(id -u):$(id -g) dist
fi
