#!/usr/bin/env bash

echo -e "\033[0;30;47m Bundling spec \033[0m"
docker compose run --rm bundler bash -c "
mkdir -p dist
json-refs resolve schema.json -f > dist/swagger.json
"

echo -e "\033[0;30;47m Injecting vars \033[0m"
# Escape "/" characters to avoid conflict with sed.
RELEASE_VERSION=${RELEASE_VERSION//\//\\/}

docker compose run --rm bundler bash -c "
sed -i 's/\$RELEASE_VERSION/${RELEASE_VERSION}/' dist/swagger.json
"
