#!/usr/bin/env bash

echo -e "\033[0;30;47m Starting containers \033[0m"
${COMPOSE} up -d carrier-specification
./mp.sh  bundle

echo -e "\033[0;30;47m ReDoc running on \033[0m http://localhost:${REDOC_PORT}"
